In [63]:
import os
import pandas as pd

In [109]:
data_dir = '/opt/ml/input/data/train_dataset'
file_name = 'train_all_three_basic_stats_ug_filtered.csv'
test_file_name = 'test_all_three_basic_stats_ug_filtered.csv'

In [123]:
csv_file_path_to_load = os.path.join(data_dir, file_name)
df = pd.read_csv(csv_file_path_to_load)

csv_file_path_to_load = os.path.join(data_dir, test_file_name)
test_df = pd.read_csv(csv_file_path_to_load)

In [124]:
df

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,elapsed,assessment_category,elapsed_time,testId_answer_rate,...,knowledge_tag_mean,knowledge_tag_sum,assessment_category_mean,et_by_kt,et_by_as,answer_mean,UserGroup,UserGroup_answer_mean,UserGroup_time_mean,KnowledgeTagGroup
0,0,A080129001,A080000129,1,2020-12-23 03:35:32,2723,22.000000,8,3.091042,0.360111,...,0.476454,344.0,0.502598,2.975214,3.093141,0.630872,7,0.617660,54.918482,57
1,0,A080129002,A080000129,1,2020-12-23 03:35:54,2723,86.000000,8,4.454347,0.360111,...,0.476454,344.0,0.502598,2.975214,2.857286,0.630872,7,0.617660,54.918482,57
2,0,A080129003,A080000129,0,2020-12-23 03:37:20,2725,83.000000,8,4.418841,0.360111,...,0.301939,436.0,0.502598,2.734488,2.473111,0.630872,7,0.617660,54.918482,57
3,0,A080129004,A080000129,1,2020-12-23 03:38:43,2725,91.000000,8,4.510860,0.360111,...,0.301939,436.0,0.502598,2.734488,2.499002,0.630872,7,0.617660,54.918482,57
4,0,A080129005,A080000129,0,2020-12-23 03:40:14,2725,5.000000,8,1.609438,0.360111,...,0.301939,436.0,0.502598,2.734488,2.583565,0.630872,7,0.617660,54.918482,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160922,7440,A030197005,A030000197,0,2020-10-21 08:33:20,1984,47.067734,3,3.851588,0.738462,...,0.749632,2039.0,0.702238,3.720730,4.378075,0.400000,12,0.369192,32.283025,50
160923,7441,A040165001,A040000165,1,2020-08-21 01:06:39,8836,11.000000,4,2.397895,0.655109,...,0.697874,2199.0,0.684056,3.369100,3.007435,0.555556,9,0.538077,47.498037,152
160924,7441,A040165002,A040000165,1,2020-08-21 01:06:50,8836,46.000000,4,3.828641,0.655109,...,0.697874,2199.0,0.684056,3.369100,2.815377,0.555556,9,0.538077,47.498037,152
160925,7441,A040165003,A040000165,1,2020-08-21 01:07:36,8836,73.000000,4,4.290459,0.655109,...,0.697874,2199.0,0.684056,3.369100,4.303724,0.555556,9,0.538077,47.498037,152
160926,7441,A040165004,A040000165,1,2020-08-21 01:08:49,8836,38.628696,4,3.653995,0.655109,...,0.697874,2199.0,0.684056,3.369100,3.586170,0.555556,9,0.538077,47.498037,152

In [120]:
test_df

,userID,assessmentItemID,testId,answerCode,Timestamp,KnowledgeTag,elapsed,testId_answer_rate,testId_answer_sum,assessmentItemID_answer_rate,...,assessment_category,assessment_category_mean,elapsed_time,et_by_kt,et_by_as,answer_mean,UserGroup,UserGroup_answer_mean,UserGroup_time_mean,KnowledgeTagGroup
0,3,A050108001,A050000108,1,2020-08-09 14:15:42,5283,41.00000,0.804718,1228.0,0.857798,...,5,0.658208,3.713572,3.540220,3.419548,0.692754,4,0.712476,61.265656,88
1,3,A050108002,A050000108,1,2020-08-09 14:16:23,5283,11.00000,0.804718,1228.0,0.834862,...,5,0.658208,2.397895,3.540220,2.819150,0.692754,4,0.712476,61.265656,88
2,3,A050108003,A050000108,1,2020-08-09 14:16:34,5283,48.00000,0.804718,1228.0,0.807339,...,5,0.658208,3.871201,3.540220,3.516157,0.692754,4,0.712476,61.265656,88
3,3,A050108004,A050000108,1,2020-08-09 14:17:22,5283,53.00000,0.804718,1228.0,0.866972,...,5,0.658208,3.970292,3.540220,2.795905,0.692754,4,0.712476,61.265656,88
4,3,A050108005,A050000108,1,2020-08-09 14:18:15,5283,27.00000,0.804718,1228.0,0.821101,...,5,0.658208,3.295837,3.540220,3.227989,0.692754,4,0.712476,61.265656,88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18233,7439,A040130001,A040000130,0,2020-10-14 23:07:23,8832,18.00000,0.644961,832.0,0.445736,...,4,0.684056,2.890372,3.341341,3.502416,0.733333,4,0.712476,61.265656,152
18234,7439,A040130002,A040000130,1,2020-10-14 23:07:41,8832,21.00000,0.644961,832.0,0.476744,...,4,0.684056,3.044522,3.341341,3.004329,0.733333,4,0.712476,61.265656,152
18235,7439,A040130003,A040000130,1,2020-10-14 23:08:02,8244,89.00000,0.644961,832.0,0.860465,...,4,0.684056,4.488636,3.870061,3.535097,0.733333,4,0.712476,61.265656,146
18236,7439,A040130004,A040000130,1,2020-10-14 23:09:31,8244,32.00000,0.644961,832.0,0.825581,...,4,0.684056,3.465736,3.870061,3.795552,0.733333,4,0.712476,61.265656,146
18237,7439,A040130005,A040000130,-1,2020-10-14 23:10:03,8832,27.56193,0.644961,832.0,0.616279,...,4,0.684056,3.316435,3.341341,3.550073,0.733333,4,0.712476,61.265656,152

In [121]:
KnowledgeTagGroup_answer_mean = df.groupby(['KnowledgeTagGroup'])['answerCode'].agg(['mean']).to_dict()
KnowledgeTagGroup_time_mean = df.groupby(['KnowledgeTagGroup'])['elapsed'].agg(['mean']).to_dict()

df['KnowledgeTagGroup_answer_mean'] = df.KnowledgeTagGroup.map(KnowledgeTagGroup_answer_mean['mean'])
df['KnowledgeTagGroup_time_mean'] = df.KnowledgeTagGroup.map(KnowledgeTagGroup_time_mean['mean'])

test_df['KnowledgeTagGroup_answer_mean'] = test_df.KnowledgeTagGroup.map(KnowledgeTagGroup_answer_mean['mean'])
test_df['KnowledgeTagGroup_time_mean'] = test_df.KnowledgeTagGroup.map(KnowledgeTagGroup_time_mean['mean'])

In [103]:
# test_df['KnowledgeTagGroup_answer_mean'] = test_df.KnowledgeTagGroup.map(KnowledgeTagGroup_answer_mean['mean'])
# test_df['KnowledgeTagGroup_time_mean'] = test_df.KnowledgeTagGroup.map(KnowledgeTagGroup_time_mean['mean'])
# test_df['UserGroup_time_mean'] = test_df.KnowledgeTagGroup.map(KnowledgeTagGroup_time_mean['mean'])
# test_df['User_KnowledgeTagGroup_time_mean'] = test_df.groupby(['userID', 'KnowledgeTagGroup'])['elapsed'].transform('mean')

# test_df['UserGroup_time_mean'] = test_df.UserGroup.map(UserGroup_time_mean['mean'])

In [105]:
train_name = f"{file_name.split('.')[0]}_gy_new.csv"
test_name = f"{test_file_name.split('.')[0]}_gy_new.csv"

df.to_csv(os.path.join(data_dir, train_name), sep=',', index=False)
test_df.to_csv(os.path.join(data_dir, test_name), sep=',', index=False)